service: get-url
app: presigned-upload
org: perfectlive

# AWS provider and env vars
provider:
  name: aws
  runtime: nodejs16.x
  environment:
    BUCKET_NAME: ${param:BUCKET_NAME}
    REGION: ${param:REGION}

# SLS plugins
plugins:
  - serverless-offline
  - serverless-plugin-typescript

# SLS lambda function
functions:
  getPresignedPostData:
    handler: handler.getPreSignedURLToPostS3
    events:
      - http:
          path: get-presigned-url
          method: post
          cors: true
